/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndividualsRouteImport } from './routes/individuals'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamiliesNewRouteImport } from './routes/families.new'
import { Route as FamiliesIdRouteImport } from './routes/families.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsRoute = IndividualsRouteImport.update({
  id: '/individuals',
  path: '/individuals',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesNewRoute = FamiliesNewRouteImport.update({
  id: '/families/new',
  path: '/families/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIdRoute = FamiliesIdRouteImport.update({
  id: '/families/$id',
  path: '/families/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/individuals': typeof IndividualsRoute
  '/search': typeof SearchRoute
  '/families/$id': typeof FamiliesIdRoute
  '/families/new': typeof FamiliesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/individuals': typeof IndividualsRoute
  '/search': typeof SearchRoute
  '/families/$id': typeof FamiliesIdRoute
  '/families/new': typeof FamiliesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/individuals': typeof IndividualsRoute
  '/search': typeof SearchRoute
  '/families/$id': typeof FamiliesIdRoute
  '/families/new': typeof FamiliesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/individuals'
    | '/search'
    | '/families/$id'
    | '/families/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/individuals'
    | '/search'
    | '/families/$id'
    | '/families/new'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/individuals'
    | '/search'
    | '/families/$id'
    | '/families/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  IndividualsRoute: typeof IndividualsRoute
  SearchRoute: typeof SearchRoute
  FamiliesIdRoute: typeof FamiliesIdRoute
  FamiliesNewRoute: typeof FamiliesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals': {
      id: '/individuals'
      path: '/individuals'
      fullPath: '/individuals'
      preLoaderRoute: typeof IndividualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/new': {
      id: '/families/new'
      path: '/families/new'
      fullPath: '/families/new'
      preLoaderRoute: typeof FamiliesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$id': {
      id: '/families/$id'
      path: '/families/$id'
      fullPath: '/families/$id'
      preLoaderRoute: typeof FamiliesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  IndividualsRoute: IndividualsRoute,
  SearchRoute: SearchRoute,
  FamiliesIdRoute: FamiliesIdRoute,
  FamiliesNewRoute: FamiliesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
